#!/bin/bash
#
# Create a sandbox account. 

# set -o nounset
# set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"

# Output utilities
err() {
  echo -e "$@" >&2  # output to stderr
}

failed() {
  printf "\033[31m" >&1  # set to red font for stdout
  printf "$@" >&2  # output to stderr
  printf "\033[0m\n" >&1  # reset color for stdout
}

check_err() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    err "$@"
    exit "${RET}"
  fi
}

check_failed() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    failed "$@"
    exit "${RET}"
  fi
}

# Inlcude script configuration
readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
[[ -n "${SCRIPT_CONF}" ]]
check_err "Script configuration is not specified"

source "${SCRIPT_CONF}"
check_err "Failed to load script configuration: ${SCRIPT_CONF}"

readonly SCRIPT_NAME="$(basename "$0")"

# Command parameters
readonly ID="$1"
[[ -n "${ID}" ]]
check_err "Usage: ${SCRIPT_NAME} <sandbox_id>"

# Set variables
if [[ -n "${SANDBOX_USERNAME_INIT+x}" ]]; then
  readonly GROUP="${SANDBOX_USERNAME_INIT}"
else
  readonly GROUP="${DEFAULT_USERNAME_INIT}"
fi

if [[ -n "${GROUP}" ]]; then
  readonly USERNAME="${GROUP}-${ID}"
else
  readonly USERNAME="${ID}"
fi

if [[ -n "${SANDBOX_USER_HOME_ROOT}" ]]; then
  readonly USER_HOME_ROOT="${SANDBOX_USER_HOME_ROOT}"
elif [[ -n "${DEFAULT_USER_HOME_ROOT}" ]]; then
  readonly USER_HOME_ROOT="${DEFAULT_USER_HOME_ROOT}"
else
  readonly USER_HOME_ROOT="/home"
fi

readonly USER_HOME="${USER_HOME_ROOT}/$USERNAME"

if [[ -n "${SANDBOX_PASSWORD_INIT}" ]]; then
  readonly PASSWORD="${SANDBOX_PASSWORD_INIT}${ID}"
else
  readonly PASSWORD="${DEFAULT_PASSWORD_INIT}${ID}"
fi

if [[ -n "${SANDBOX_PEM_HOME}" ]]; then
  readonly PEM_HOME="${SANDBOX_PEM_HOME}"
else
  readonly PEM_HOME="${DEFAULT_PEM_HOME}"
fi

if [[ -n "${SANDBOX_ENV_CONF_REF_ROOT}" ]]; then
  readonly ENV_CONF_REF_ROOT="${SANDBOX_ENV_CONF_REF_ROOT}"
else
  readonly ENV_CONF_REF_ROOT="${DEFAULT_ENV_CONF_REF_ROOT}"
fi

if [[ -n "${SANDBOX_ENV_CONF_LIST}" ]]; then
  readonly ENV_CONF_LIST="${SANDBOX_ENV_CONF_LIST}"
else
  readonly ENV_CONF_LIST="${DEFAULT_ENV_CONF_LIST}"
fi

if [[ -n "${SANDBOX_ADD_ON_GROUPS}" ]]; then
  readonly ADD_ON_GROUPS="${SANDBOX_ADD_ON_GROUPS}"
else
  readonly ADD_ON_GROUPS="${DEFAULT_ADD_ON_GROUPS}"
fi

readonly GROUP_LIST="${GROUP} ${ADD_ON_GROUPS}"

# Create groups, if necessary
for G in ${GROUP_LIST}; do
  [[ -n "$(getent group "${G}")" ]] || (sudo groupadd "${G}")
  check_failed "failed to create non-existing group '${G}'"
done

# Delete the group named after the account
[[ -z "$(getent group "${USERNAME}")" ]] || (sudo groupdel "${USERNAME}")
check_failed "failed to delete existing group '${USERNAME}'"

# Create account
create_account() {
  sudo useradd "$1" "${2:+"-G"}" "$2" -m -d "$3" -s /bin/bash
}
create_account "${USERNAME}" "${GROUP}" "${USER_HOME}"
check_failed "failed to create account '${USERNAME}'"

for G in ${ADD_ON_GROUPS}; do
  sudo usermod -a -G "${G}" "${USERNAME}" 
done

# Configure account password
echo -e "${PASSWORD}\n${PASSWORD}" | sudo passwd "${USERNAME}" > /dev/null 2>&1
check_failed "failed to set password for account '${USERNAME}'"

# Confiugre enviornment
sudo chmod 777 "${USER_HOME}"

init_conf() {
  local -r SRC_CONF_FILE="${ENV_CONF_REF_ROOT}/$1"
  if [[ -f "${SRC_CONF_FILE}" ]]; then
    local -r DST_CONF_FILE="${USER_HOME}/$1"
    sudo touch "${DST_CONF_FILE}"
    sudo chmod 722 "${DST_CONF_FILE}"
    sudo cat "${SRC_CONF_FILE}" > "${DST_CONF_FILE}"
    sudo chmod 644 "${DST_CONF_FILE}"
    sudo chown "${USERNAME}":"${USERNAME}" "${DST_CONF_FILE}"
  fi
}

for CONF_FILE in ${ENV_CONF_LIST}; do
  init_conf "${CONF_FILE}"
done

# Generate SSH keys (private/public)
readonly USER_SSH_ROOT="${USER_HOME}/.ssh"
sudo mkdir -p "${USER_SSH_ROOT}"
sudo ssh-keygen -t rsa -f "${USER_SSH_ROOT}/id_rsa" -P '' -q
sudo touch "${USER_SSH_ROOT}/authorized_keys"
sudo chmod 722 "${USER_SSH_ROOT}/authorized_keys"
sudo cat "${USER_SSH_ROOT}/id_rsa.pub" >> "${USER_SSH_ROOT}/authorized_keys"
sudo chmod 600 "${USER_SSH_ROOT}/authorized_keys"
sudo mkdir -p "${PEM_HOME}"
sudo cp -f "${USER_SSH_ROOT}/id_rsa" "${PEM_HOME}/${USERNAME}.pem"
sudo chmod +r "${PEM_HOME}/${USERNAME}.pem" 
sudo chown -R "${USERNAME}":"${USERNAME}" "${USER_SSH_ROOT}"
sudo chmod 700 "${USER_HOME}"

# End of script
echo "account '${USERNAME}' has been created successfully"
exit 0
