#!/bin/bash
#
# Update the password of a sandbox account.

#set -o nounset
#set -o errexit
set -o pipefail

# Include libraries
readonly SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd -P)"
source "${SCRIPT_HOME}/../_common_lib/output_utils.sh"
source "${SCRIPT_HOME}/lib/load_script_conf.sh"

# Command parameters
readonly ID="$1"
readonly PASSWORD="$2"
[[ -n "${ID}" ]] && [[ -n "${PASSWORD}" ]]
check_cmd_args "<sandbox_id>" "<password>"

# Set variables
readonly USERNAME_INIT="${SANDBOX_USERNAME_INIT-${DEFAULT_USERNAME_INIT}}"

readonly USERNAME="${USERNAME_INIT:+"${USERNAME_INIT}-"}${ID}"

# Validate the existence of account
id -u "${USERNAME}" > /dev/null 2>&1
check_failed "account '${USERNAME}' does not exist"

# Update account password
echo -e "${PASSWORD}\n${PASSWORD}" | sudo passwd "${USERNAME}" > /dev/null 2>&1
check_failed "failed to update password"

# End of script
echo "password updated successfully"
exit 0
