#!/bin/bash
#
# Delete a sandbox account. 

#set -o nounset
#set -o errexit
set -o pipefail

# Include libraries
readonly SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd -P)"
source "${SCRIPT_HOME}/../_common_lib/output_utils.sh"
source "${SCRIPT_HOME}/lib/load_script_conf.sh"

# Command parameters
readonly ID="$1"
[[ -n "${ID}" ]]
check_cmd_args "<sandbox_id>"

# Set variables
readonly USERNAME_INIT="${SANDBOX_USERNAME_INIT-${DEFAULT_USERNAME_INIT}}"

readonly USERNAME="${USERNAME_INIT:+"${USERNAME_INIT}-"}${ID}"

readonly USER_HOME_ROOT=\
"${SANDBOX_USER_HOME_ROOT:-${DEFAULT_USER_HOME_ROOT:-$(dirname "${HOME}")}}"

readonly PEM_HOME="${SANDBOX_PEM_HOME-${DEFAULT_PEM_HOME}}"

# Delete account and the associated home folder and mailbox file
sudo rm -rf "${USER_HOME_ROOT}/${USERNAME}" && 
sudo rm -f "/var/spool/mail/${USERNAME}" && 
sudo userdel "${USERNAME}"
check_failed "failed to delete account '${USERNAME}'"

# Delete the associated private key
if [[ -n "${PEM_HOME}" ]]; then
  sudo rm -f "${PEM_HOME}/${USERNAME}.pem"
fi

# End of script
echo "account '${USERNAME}' has been deleted successfully"
exit 0
