#!/bin/bash
#set -o nounset
#set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="$HOME/sandbox/scripts/sandbox_script.conf.default"

# Inlcude script configuration
if [[ $SANDBOX_SCRIPT_CONF ]]; then
  source $SANDBOX_SCRIPT_CONF
else
  source $DEFAULT_SANDBOX_SCRIPT_CONF
fi

# Validate command parameters
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <sandbox_id>" >&2
  exit 1
fi

# Set variables
ID="$1"

USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
if [[ $SANDBOX_USERNAME_INIT ]]; then
  USERNAME="${SANDBOX_USERNAME_INIT}-${ID}"
fi

PEM_HOME="${DEFAULT_PEM_HOME}"
if [[ $SANDBOX_PEM_HOME ]]; then
  PEM_HOME="${SANDBOX_PEM_HOME}"
fi

RED="\033[31m"
NE="\033[0m"

# Delete account and the associated home folder and mailbox file
sudo rm -rf /home/${USERNAME} && 
sudo rm -f /var/spool/mail/${USERNAME} && 
sudo userdel $USERNAME

RET="$?"
if [[ ${RET} -eq 0 ]]; then
  echo -e "account '${USERNAME}' has been deleted successfully"
  sudo rm -f ${PEM_HOME}/${USERNAME}.pem
else
  echo -e "${RED}failed to delete account '${USERNAME}'${NE}" >&2
fi

# End of script
exit ${RET}
