#!/bin/bash
#
# List all sandbox accounts.

#set -o nounset
set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"

# Output utilities
err() {
  echo -e "$@" >&2  # output to stderr
}

failed() {
  printf "\033[31m" >&1  # set to red font for stdout
  printf "$@" >&2  # output to stderr
  printf "\033[0m\n" >&1  # reset color for stdout
}

check_err() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    err "$@"
    exit "${RET}"
  fi
}

check_failed() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    failed "$@"
    exit "${RET}"
  fi
}

# Inlcude script configuration
readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
[[ -n "${SCRIPT_CONF}" ]]
check_err "Script configuration is not specified"

source "${SCRIPT_CONF}"
check_err "Failed to load script configuration: ${SCRIPT_CONF}"

readonly SCRIPT_NAME="$(basename "$0")"

# Set variables
if [[ -n "${SANDBOX_USERNAME_INIT}" ]]; then
  readonly USERNAME_INIT="${SANDBOX_USERNAME_INIT}"
else
  readonly USERNAME_INIT="${DEFAULT_USERNAME_INIT}"
fi

# List usernames according to the specified pattern
cut -d: -f1 /etc/passwd | grep "${USERNAME_INIT}.*"

# End of script
exit "$?"
