#!/bin/bash
#
# Install ForkBase dependencies on Ubuntu.
#
# https://github.com/streamjoin/forkbase-doc/blob/master/installation/install-deps.md

set -o errexit
set -o pipefail

# Include libraries
readonly SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd -P)"
source "${FAIRY_HOME:-${SCRIPT_HOME}/..}/_common_lib/output_utils.sh"

# Set variables
DEPS_DIR="/usr/local/share"
BASH_PROFILE="${HOME}/.profile"
TEMP_DIR="$(cd ${HOME}; pwd -P)/deps_install"

CMAKE_VER="3.13.4"

WORK_DIR="$(pwd -P)"
[[ "${WORK_DIR}" != "${TEMP_DIR}" ]]
check_err "The temporary directory cannot be the current working directory"

mkdir -p "${TEMP_DIR}"

# Instal compilation tools
sudo apt install build-essential autoconf pkg-config libtool git

# Set environment variables
cat >> "${BASH_PROFILE}" <<- EndOfMsg
export SHARE_HOME="${DEPS_DIR}"
export NCORES="$(cat /proc/cpuinfo | grep "cpu cores" | uniq | awk '{print $NF}')"

EndOfMsg
source "${BASH_PROFILE}"

# CMake
cd "${TEMP_DIR}"
wget "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}.tar.gz"
tar xzf "cmake-${CMAKE_VER}.tar.gz"

cd "cmake-${CMAKE_VER}"
./bootstrap --prefix="${SHARE_HOME}/cmake" --parallel="${NCORES}"
make -j "${NCORES}"
sudo make install

cat >> "${BASH_PROFILE}" <<- EndOfMsg
# CMake
export CMAKE_HOME="\${SHARE_HOME}/cmake"
export PATH="\${CMAKE_HOME}/bin:\${PATH}"

EndOfMsg
source "${BASH_PROFILE}"

# End of script
cd "${WORK_DIR}"
rm -rf "${TEMP_DIR}"
exit 0

