#!/usr/bin/env bash
#
# Generate SSH key pair for current account or a specified account.

set -o nounset
# set -o errexit
set -o pipefail

# Include libraries
readonly SCRIPT_HOME="$(cd "$(dirname -- "$0")"; pwd -P)"
source "${FAIRY_HOME:-${SCRIPT_HOME}/..}/_common_lib/output_utils.sh"

# Command parameters
readonly USERNAME="${1:-${USER}}"

# Set variables
readonly USER_SSH_ROOT="$(getent passwd "${USERNAME}" | cut -d: -f6)/.ssh"

# Validate the existence of user account
id -u "${USERNAME}" > /dev/null 2>&1
check_err "account '${USERNAME}' does not exist"

# Generate SSH keys (private/public)
mkdir -p "${USER_SSH_ROOT}"
chown -R "${USERNAME}":"${USERNAME}" "${USER_SSH_ROOT}"
ssh-keygen -t rsa -f "${USER_SSH_ROOT}/id_rsa" -P '' -q

# Authorize the public key for the user account
touch "${USER_SSH_ROOT}/authorized_keys"
chmod 722 "${USER_SSH_ROOT}/authorized_keys"
cat "${USER_SSH_ROOT}/id_rsa.pub" >> "${USER_SSH_ROOT}/authorized_keys"
chmod 600 "${USER_SSH_ROOT}/authorized_keys"

# End of script
info "SSH key pair has been generated for account '${USERNAME}'"
exit 0
