#!/bin/bash
#
# Generate SSH key pair for current account or a specified account.

set -o nounset
set -o errexit
set -o pipefail

# Output utilities
err() {
  echo -e "$@" >&2  # output to stderr
}

failed() {
  printf "\033[31m" >&1  # set to red font for stdout
  printf "$@" >&2  # output to stderr
  printf "\033[0m\n" >&1  # reset color for stdout
}

check_err() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    err "$@"
    exit "${RET}"
  fi
}

check_failed() {
  local -r RET="$?"
  if [[ "${RET}" -ne 0 ]]; then
    failed "$@"
    exit "${RET}"
  fi
}

# Command parameters
readonly USERNAME="${1:-${USER}}"

# Set variables
readonly USER_SSH_ROOT="/home/$USERNAME/.ssh"

# Validate the existence of user account
if ! id -u "${USERNAME}" > /dev/null 2>&1; then
  failed "account '${USERNAME}' does not exist$"
  exit 2
fi

# Generate SSH keys (private/public)
mkdir -p "${USER_SSH_ROOT}"
chown -R "${USERNAME}":"${USERNAME}" "${USER_SSH_ROOT}"
ssh-keygen -t rsa -f "${USER_SSH_ROOT}/id_rsa" -P '' -q

# Authorize the public key for the user account
touch "${USER_SSH_ROOT}/authorized_keys"
chmod 722 "${USER_SSH_ROOT}/authorized_keys"
cat "${USER_SSH_ROOT}/id_rsa.pub" >> "${USER_SSH_ROOT}/authorized_keys"
chmod 600 "${USER_SSH_ROOT}/authorized_keys"

# End of script
echo "SSH key pair has been generated for account '${USERNAME}'"
exit 0
