#!/bin/bash
#set -o nounset
set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="/home/ubuntu/sandbox_scripts/sandbox_script.conf"

# Inlcude script configuration
if [[ -z $SANDBOX_SCRIPT_CONF ]]; then
  source $DEFAULT_SANDBOX_SCRIPT_CONF
else
  source $SANDBOX_SCRIPT_CONF
fi

# Validate command parameters
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <sandbox_id>"
  exit 1
fi

# Construct variables
ID="$1"
USERNAME="${DEFAULT_USERNAME_INIT}${ID}"
PASSWORD="${DEFAULT_PASSWORD_INIT}${ID}"
GROUP="$DEFAULT_USERNAME_INIT"
USER_HOME="/home/$USERNAME"

# Create account
sudo useradd -G $GROUP $USERNAME -m -s /bin/bash

# Configure account password
echo -e "${PASSWORD}\n${PASSWORD}" | sudo passwd -q ${USERNAME} >> /dev/null 2>&1

# Confiugre enviornment
init_conf() {
  sudo touch $USER_HOME/$1
  sudo chmod 722 $USER_HOME/$1
  sudo cat $DEFAULT_ENV_CONF_REF_ROOT/$1 > $USER_HOME/$1
  sudo chmod 644 $USER_HOME/$1
  sudo chown $USERNAME:$USERNAME $USER_HOME/$1
}

init_conf .bash_aliases
init_conf .profile
init_conf .vimrc

# Generate SSH keys (private/public)
USER_SSH_ROOT="$USER_HOME/.ssh"
sudo mkdir -p $USER_SSH_ROOT
sudo ssh-keygen -t rsa -f $USER_SSH_ROOT/id_rsa -P '' -q
sudo touch $USER_SSH_ROOT/authorized_keys
sudo chmod 722 $USER_SSH_ROOT/authorized_keys
sudo cat $USER_SSH_ROOT/id_rsa.pub >> $USER_SSH_ROOT/authorized_keys
sudo chmod 600 $USER_SSH_ROOT/authorized_keys
sudo cp -f $USER_SSH_ROOT/id_rsa $DEFAULT_PEM_HOME/${USERNAME}.pem
sudo chmod +r $DEFAULT_PEM_HOME/${USERNAME}.pem 
sudo chown -R $USERNAME:$USERNAME $USER_SSH_ROOT
sudo chmod 700 $USER_HOME

# End of script
echo -e "account '${USERNAME}' has been created successfully"
exit 0
