#!/bin/bash
#set -o nounset
#set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="/home/ubuntu/sandbox_scripts/sandbox_script.conf"

# Inlcude script configuration
if [[ -z $SANDBOX_SCRIPT_CONF ]]; then
  source $DEFAULT_SANDBOX_SCRIPT_CONF
else
  source $SANDBOX_SCRIPT_CONF
fi

# Validate command parameters
if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <sandbox_id> <password>"
  exit 1
fi

# Construct variables
ID="$1"
PASSWORD="$2"
USERNAME="${DEFAULT_USERNAME_INIT}${ID}"

# Update account password
echo -e "${PASSWORD}\n${PASSWORD}" | sudo passwd -q ${USERNAME} >> /dev/null 2>&1

RET="$?"

# End of script
BOLD="\033[1m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
NE="\033[0m"

if [[ ${RET} -eq 0 ]]; then
  echo -e "password updated successfully"
else
  echo -e "${RED}failed to update password${NE}"
fi

exit ${RET}
