#!/bin/bash
#set -o nounset
#set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox_scripts/sandbox_script.conf.default"

# Inlcude script configuration
if [[ $SANDBOX_SCRIPT_CONF ]]; then
	source $SANDBOX_SCRIPT_CONF
else
	source $DEFAULT_SANDBOX_SCRIPT_CONF
fi

# Validate command parameters
if [[ $# -lt 2 ]]; then
	echo "Usage: $0 <sandbox_id> <password>"
	exit 1
fi

# Set variables
ID="$1"
PASSWORD="$2"

USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
if [[ $SANDBOX_USERNAME_INIT ]]; then
	USERNAME="${SANDBOX_USERNAME_INIT}-${ID}"
fi

RED="\033[31m"
NE="\033[0m"

# Update account password
echo -e "${PASSWORD}\n${PASSWORD}" | sudo passwd ${USERNAME} >> /dev/null 2>&1

RET="$?"
if [[ ${RET} -eq 0 ]]; then
	echo -e "password updated successfully"
else
	echo -e "${RED}failed to update password${NE}"
fi

# End of script
exit ${RET}
