#!/bin/bash
#set -o nounset
set -o errexit
set -o pipefail

DEFAULT_SANDBOX_SCRIPT_CONF="/home/ubuntu/sandbox_scripts/sandbox_script.conf"

# Inlcude script configuration
if [[ -z $SANDBOX_SCRIPT_CONF ]]; then
  source $DEFAULT_SANDBOX_SCRIPT_CONF
else
  source $SANDBOX_SCRIPT_CONF
fi

# list usernames according to the specified pattern
cut -d: -f1 /etc/passwd | grep ${DEFAULT_USERNAME_INIT}.*

# End of script
exit $?
